version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - '8500:3000'
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - '8501:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'